feat: add my cluster modif

diff --git a/.github/workflows/terraform_automatic_plan.yaml b/.github/workflows/terraform_automatic_plan.yaml
--- a/.github/workflows/terraform_automatic_plan.yaml
+++ b/.github/workflows/terraform_automatic_plan.yaml
@@ -1,108 +1,108 @@
----
-name: "Automatic terraform plan on PR"
+# ---
+# name: "Automatic terraform plan on PR"
 
-on:
-  pull_request:
-    branches:
-    - main
+# on:
+#   pull_request:
+#     branches:
+#     - main
 
-jobs:
-  terraform-plan:
-    runs-on: ubuntu-latest
-    env:
-      TF_ACTION_WORKING_DIR: .
-      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
+# jobs:
+#   terraform-plan:
+#     runs-on: ubuntu-latest
+#     env:
+#       TF_ACTION_WORKING_DIR: .
+#       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+#       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+#       AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
 
-    steps:
+#     steps:
 
-    - name: "Checkout the repository"
-      uses: actions/checkout@v3
+#     - name: "Checkout the repository"
+#       uses: actions/checkout@v3
 
-    - name: "Setup Terraform"
-      uses: hashicorp/setup-terraform@v2
+#     - name: "Setup Terraform"
+#       uses: hashicorp/setup-terraform@v2
 
-    - name: "Run terraform fmt -check"
-      id: fmt
-      run: "terraform fmt -check"
+#     - name: "Run terraform fmt -check"
+#       id: fmt
+#       run: "terraform fmt -check"
 
-    - name: "Run terraform init"
-      id: init
-      run: "terraform init -no-color"
+#     - name: "Run terraform init"
+#       id: init
+#       run: "terraform init -no-color"
     
-    - name: "Run terraform validate"
-      id: validate
-      run: "terraform validate -no-color"
+#     - name: "Run terraform validate"
+#       id: validate
+#       run: "terraform validate -no-color"
 
-    - name: "Run terraform plan"
-      id: plan
-      run: "terraform plan -no-color -input=false"
-      continue-on-error: true # This is in order to continue even if there is an error so we can get the output
+#     - name: "Run terraform plan"
+#       id: plan
+#       run: "terraform plan -no-color -input=false"
+#       continue-on-error: true # This is in order to continue even if there is an error so we can get the output
 
-    - name: "Add a comment to the PR with the result of the previous steps"
-      uses: actions/github-script@v6
-      if: github.event_name == 'pull_request'
-      env:
-        VALIDATE: "$ terraform validate\n${{ steps.validate.outputs.stdout }}"
-        PLAN: "$ terraform plan\n${{ steps.plan.outputs.stdout }}"
-      with:
-        github-token: ${{ secrets.GITHUB_TOKEN }}
-        script: |
-          // 1. Retrieve existing bot comments for the PR
-          const { data: comments } = await github.rest.issues.listComments({
-            owner: context.repo.owner,
-            repo: context.repo.repo,
-            issue_number: context.issue.number,
-          })
-          const botComment = comments.find(comment => {
-            return comment.user.type === 'Bot' && comment.body.includes('Terraform format and style:')
-          })
+#     - name: "Add a comment to the PR with the result of the previous steps"
+#       uses: actions/github-script@v6
+#       if: github.event_name == 'pull_request'
+#       env:
+#         VALIDATE: "$ terraform validate\n${{ steps.validate.outputs.stdout }}"
+#         PLAN: "$ terraform plan\n${{ steps.plan.outputs.stdout }}"
+#       with:
+#         github-token: ${{ secrets.GITHUB_TOKEN }}
+#         script: |
+#           // 1. Retrieve existing bot comments for the PR
+#           const { data: comments } = await github.rest.issues.listComments({
+#             owner: context.repo.owner,
+#             repo: context.repo.repo,
+#             issue_number: context.issue.number,
+#           })
+#           const botComment = comments.find(comment => {
+#             return comment.user.type === 'Bot' && comment.body.includes('Terraform format and style:')
+#           })
 
-          // 2. Prepare format of the comment
-          const output = `#### Terraform format and style: \`${{ steps.fmt.outcome }}\`
-          #### Terraform initialization: \`${{ steps.init.outcome }}\`
-          #### Terraform validation: \`${{ steps.validate.outcome }}\`
+#           // 2. Prepare format of the comment
+#           const output = `#### Terraform format and style: \`${{ steps.fmt.outcome }}\`
+#           #### Terraform initialization: \`${{ steps.init.outcome }}\`
+#           #### Terraform validation: \`${{ steps.validate.outcome }}\`
           
-          <details><summary>Show validation output</summary>
+#           <details><summary>Show validation output</summary>
           
-          \`\`\`\n
-          ${process.env.VALIDATE}
-          \`\`\`
+#           \`\`\`\n
+#           ${process.env.VALIDATE}
+#           \`\`\`
           
-          </details>
+#           </details>
           
-          #### Terraform plan: \`${{ steps.plan.outcome }}\`
+#           #### Terraform plan: \`${{ steps.plan.outcome }}\`
           
-          <details><summary>Show plan</summary>
+#           <details><summary>Show plan</summary>
           
-          \`\`\`\n
-          ${process.env.PLAN}
-          \`\`\`
+#           \`\`\`\n
+#           ${process.env.PLAN}
+#           \`\`\`
           
-          </details>
+#           </details>
           
-          *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;
+#           *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;
           
-          // 3. If we have a comment, update it, otherwise create a new one
-          if (botComment) {
-            github.rest.issues.updateComment({
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              comment_id: botComment.id,
-              body: output
-            })
-          } else {
-            github.rest.issues.createComment({
-              issue_number: context.issue.number,
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              body: output
-            })
-          }
+#           // 3. If we have a comment, update it, otherwise create a new one
+#           if (botComment) {
+#             github.rest.issues.updateComment({
+#               owner: context.repo.owner,
+#               repo: context.repo.repo,
+#               comment_id: botComment.id,
+#               body: output
+#             })
+#           } else {
+#             github.rest.issues.createComment({
+#               issue_number: context.issue.number,
+#               owner: context.repo.owner,
+#               repo: context.repo.repo,
+#               body: output
+#             })
+#           }
 
-    # This step is needed so the workflow appears as unsuccessful in the event of a failed terraform plan
-    # We only need this because we used `continue-on-error: true` on the `terraform plan` step
-    - name: "Check that the plan was successful otherwise throw an error and quit"
-      if: steps.plan.outcome == 'failure'
-      run: "exit 1"
+#     # This step is needed so the workflow appears as unsuccessful in the event of a failed terraform plan
+#     # We only need this because we used `continue-on-error: true` on the `terraform plan` step
+#     - name: "Check that the plan was successful otherwise throw an error and quit"
+#       if: steps.plan.outcome == 'failure'
+#       run: "exit 1"
